--
-- File generated with SQLiteStudio v3.4.4 on Tue Nov 12 17:04:24 2024
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: role_has_permissions
CREATE TABLE IF NOT EXISTS "role_has_permissions" ("permission_id" integer not null, "role_id" integer not null, foreign key("permission_id") references "permissions"("id") on delete cascade, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("permission_id", "role_id"));
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (1, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (2, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (3, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (4, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (5, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (6, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (7, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (8, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (9, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (10, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (11, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (12, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (13, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (14, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (15, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (16, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (17, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (18, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (19, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (20, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (21, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (22, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (23, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (24, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (25, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (26, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (27, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (28, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (29, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (30, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (31, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (32, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (33, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (34, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (35, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (36, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (37, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (38, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (39, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (40, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (41, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (42, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (43, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (44, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (45, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (46, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (47, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (48, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (49, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (50, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (51, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (52, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (53, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (54, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (55, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (56, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (57, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (58, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (59, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (60, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (61, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (62, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (63, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (64, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (65, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (66, 1);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (1, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (2, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (3, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (4, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (5, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (6, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (7, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (8, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (9, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (10, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (11, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (12, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (25, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (26, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (27, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (28, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (29, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (30, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (31, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (32, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (33, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (34, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (35, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (36, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (37, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (38, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (39, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (40, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (41, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (42, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (43, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (44, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (45, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (46, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (47, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (48, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (49, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (50, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (51, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (52, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (53, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (54, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (55, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (56, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (57, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (58, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (59, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (60, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (61, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (62, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (63, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (64, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (65, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (66, 3);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (1, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (2, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (25, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (26, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (27, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (28, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (33, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (43, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (45, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (46, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (51, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (44, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (55, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (57, 2);
INSERT INTO role_has_permissions (permission_id, role_id) VALUES (58, 2);

-- Index: sqlite_autoindex_role_has_permissions_1
CREATE UNIQUE INDEX IF NOT EXISTS sqlite_autoindex_role_has_permissions_1 ON role_has_permissions (permission_id COLLATE BINARY, role_id COLLATE BINARY);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
